name=input("Enter your name: ")
marks=int(input("Enter your marks: "))
phone_no=int(input("Enter your phone number: "))
a="The name of the student is {}, his marks are {} and phone number is {}".format(name,marks,phone_no)
print(a)